### ISSUE TITLE
itertools

### ISSUE THREAD

**Issue by TristanLefebure** [COMBINE-lab/RapClust#15]
Hi there, 

I have RapClust failling this way:

```
tristan@umr5023-proasellus res] RapClust --config RapClust_config.yaml
2017-07-17 14:48:04 umr5023-proasellus root[14426] INFO Building multiple alignment graph
Traceback (most recent call last):
  File "/usr/local/bin/RapClust", line 106, in <module>
    processQuant()
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/RapClust", line 69, in processQuant
    eqnet.buildNetFile(sampleDirs, netFile, cutoff, auxDir)
  File "/usr/local/lib/python3.5/dist-packages/rapclust/eqnet.py", line 25, in buildNetFile
    for sffile, eqfile in itertools.izip(sffiles, eqfiles):
AttributeError: module 'itertools' has no attribute 'izip'
```

Sounds like I don't have the module itertools on my system (Ubuntu LTS 16.04) and I don't see how I can get it installed... (not a python programmer, I may miss something simple...)

Any idea how to proceed ?

Thanks
--
Tristan

**Comment by rob-p** [comment]
Hi @TristanLefebure,

  This looks like a Python v2 vs. Python v3 issue (i.e., the `izip` method exists in Python v2 but was removed in Python v3).  There are a few such incompatibilities in the code, and we are working to remove them.  The most immediate solution, however, would be to try and run rapclust under a Python 2 installation.

**Comment by TristanLefebure** [comment]
Thanks, it worked!

Problem solved by restarting the install, this time doing:

`pip2 install RapClust`
